# Generated by Django 2.2.4 on 2019-10-06 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fib_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 10, 45, 45, 222120, tzinfo=utc)),
        ),
    ]
