# Generated by Django 2.2.4 on 2019-10-06 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fib', '0002_auto_20191006_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fib_data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 6, 10, 47, 1, 799428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fib_data',
            name='duretion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
